### ISSUE TITLE
NullPointerException:

### ISSUE THREAD

**Issue by builde7b0b** [builde7b0b/Java-Mini-Project---RPS#12]
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.Scanner.nextInt()" because "this.scanner" is null
	at HumanPlayer.choose(HumanPlayer.java:9)
	at Game.play(Game.java:39)
	at Main.main(Main.java:4)

**Comment by builde7b0b** [comment]
Fixed this by initializing a scanner obj in the HumanPlayer constructor
